### ISSUE TITLE
Deliverable 1 part - Task 3

### ISSUE THREAD

**Issue by bellabaohaha** [bellabaohaha/CITS5206-Gp2#14]
Add task 3 for Deliverable 1

**Comment by bellabaohaha** [comment]
Updated deliverable as task 4 - integration with user interface

**Comment by bellabaohaha** [comment]
Shorten task 4 into 1 paragraph. 
We will implement an IoT dashboard as a user interface to provide near real-time insights and analytics. The dashboard should show historical data of Soil Moisture levels that can be used to analyze other key performance indicators of farming/agriculture, e.g. yield, water used in Irrigation. The system will involve data interpretation methods like Angular Distance Weighting (ADW) to monitor moisture levels, moisture at different depths, geographic location etc. Users should be able to see the real-time data and make prompt farming decisions based on it. 
It is planned to use existing third-party products like the John Deere platform for operation. It can only be achieved if we can get Assets API access by Aug 23rd. Alternatively we can create a customized dashboard to show key metrics.

**Comment by asadmaza** [comment]
Closing see our [Google Doc](https://docs.google.com/document/d/1z4xZulRj1yGnO9NUQU9zTKsZANRpLPvfV37chAgSwRg). I've updated it to make it clearer.



![Image](https://github.com/user-attachments/assets/9258d415-b392-40f6-a93c-c8296645e84c)
