### ISSUE TITLE
Modification of Task2 for iot mvp

### ISSUE THREAD

**Issue by ITwoaini** [bellabaohaha/CITS5206-Gp2#23]
modification

**Comment by asadmaza** [comment]
Completed. See [Google Doc](https://docs.google.com/document/d/1z4xZulRj1yGnO9NUQU9zTKsZANRpLPvfV37chAgSwRg/) or screenshot below.



![Image](https://github.com/user-attachments/assets/33cc7146-db33-42ff-b627-f90fdcdd30cb)
