### ISSUE TITLE
Secure Google Doc

### ISSUE THREAD

**Issue by asadmaza** [bellabaohaha/CITS5206-Gp2#28]
Hey Bella,

Can you please ensure that we have a secure google doc?

Changes required:
Read only access for everyone
Write access for our group, I think you have my gmail account

**Comment by bellabaohaha** [comment]
Hi Asad, It has been done.

**Comment by asadmaza** [comment]
Thanks, closing

**Comment by asadmaza** [comment]
Thanks, closing
