### ISSUE TITLE
Create the Gantt Chart

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#31]

**Comment by asadmaza** [comment]
Hey David, I just had a quick look at what you've done, good job so far.... we still need to put in dates I provided you right and milestones like (this is not exhaustive, please check this I'm going off the dome) meeting for example the first task will require a feedback meeting on Friday, final presentation handover , deadline for final submission


Goal was to get a timeline here:
![image](https://github.com/user-attachments/assets/455687c4-3e89-446d-82a2-02e7f94bb44c)


Please see this plan [Gantt Chart#29](https://github.com/bellabaohaha/CITS5206-Gp2/issues/29) I created for more details

**Comment by David-Shang** [comment]
Problem solved
