### ISSUE TITLE
Power Management System

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#35]
Develop and test a power management system for the IoT prototype, focusing on sleep and duty cycles.

**Comment by asadmaza** [comment]
See these links about turning off GPS on T-Beam to save power after getting it once and only once on deployment:

https://meshtastic.org/docs/hardware/devices/tbeam/buttons/ - Hardware method

https://github.com/LilyGO/TTGO-T-Beam/issues/19 - SDK/Programmatic method


https://github.com/users/bellabaohaha/projects/3/views/1?pane=issue&itemId=75940821

See this if you're not sure why I linked those

**Comment by udaymithra** [comment]
For the project code to work, following libraries with respective versions needs to be installed in the Arduino IDE.
![Image](https://github.com/user-attachments/assets/c0a45b95-d3be-4acd-91dc-1fb173e90e67)

![Image](https://github.com/user-attachments/assets/ccfa86f7-534e-4035-a15a-922f9b75af40)

![Image](https://github.com/user-attachments/assets/7bc8acfa-cff0-43e6-8b58-f1c5a2471507)


In the project source code, following configuration files  and libraries need to placed at the top.

![Image](https://github.com/user-attachments/assets/a0607ed2-e35d-4fe5-8924-1eca73817324)


For setting up and optimizing the LoRa communication module, radio configuration parameters needs to be set with following values.

![Image](https://github.com/user-attachments/assets/c4392947-980b-494a-9304-44eeca90ac63)

For GPS and Serial communication, I created a gps and Serial1 objects

![Image](https://github.com/user-attachments/assets/9d127312-181c-4d6d-90d4-572849816d78)

Initialised the External LED bulb to GPIO 25 and a manual button is GPIO 38 to turn off/ turn on  gps location 

![Image](https://github.com/user-attachments/assets/0a5aee4b-93a9-47c3-b25d-c4eb59c99749)

Variables to track gps state, button state, no of times button pressed and boolean variable to know whether gps data received.
RTC_DATA_ATTR is used to retain the values during deep sleep.
![Image](https://github.com/user-attachments/assets/42b9a16c-633a-47d9-bf0a-c003af70933c)

an array is initialised to store the gps data values and a boolean variable to know the time is synced with RTC.

![Image](https://github.com/user-attachments/assets/1fb367b8-f8cd-4208-b392-b2c4fc19b0e9)

Variables used for soil moisture readings and sensors connected to GPIO pins 13,14,15. and also defined constant values which are calibrated for dry and wet conditions.

![Image](https://github.com/user-attachments/assets/cd98094a-850f-43d2-8cd1-634e6f1a8a7f)

A constant scheduledTimes array is defined which contains the time for which the system needs to wake from deep sleep.

![Image](https://github.com/user-attachments/assets/5ef9538a-ca47-42f8-afe7-074f082ae7cd)
 
**Setup() function:**
It is used to initialize LoRa and handles the system when wake up from deep sleep.
If the device woke up from deep sleep, it initializes peripherals for readings, checks if it's a scheduled time, takes readings if necessary, and then goes back to sleep.
Along with this it handles if the system is reset / power off and power on it initializes all peripherals and turns on the GPS module.

![Image](https://github.com/user-attachments/assets/cabec903-5163-4fcd-98d2-c9fb1fbfdef0)


**loop() function:**
It handles following:
**GPS Data Acquisition**: If GPS is on and data hasn't been received yet, it reads and processes GPS data.
**Deep Sleep Entry**: Once GPS is off and data is received, it calculates sleep time until the next scheduled reading and enters deep sleep.
**Battery Status Monitoring**: Continuously updates battery percentage.

![Image](https://github.com/user-attachments/assets/bd1d6144-53c4-4953-8bdf-62e183a1ed64)

**handleButtonPress() function features:**

**Button Debouncing and Press Counting**: Implements debouncing logic and counts presses to toggle GPS.
**GPS Control**: Functions to turn GPS on or off and control the LED indicator.

![Image](https://github.com/user-attachments/assets/100bb95d-b81f-4e8f-af34-c9ba6e18d69f)

**storeGPSData and printGPSData function features:**
**Data Storage:** Stores latitude, longitude, battery percentage, time, and date.
**Data Printing:** Prints GPS data to the Serial Monitor.

![Image](https://github.com/user-attachments/assets/b799e038-d5eb-4599-9b7b-58693bd1b9ad)

![Image](https://github.com/user-attachments/assets/6b303e1a-af21-4d7e-88ca-6023de0827f1)

**syncTimeWithRTC() function features:**
Synchronizes the ESP32's internal RTC with GPS time which is adjusted for AWST (UTC+8).

![Image](https://github.com/user-attachments/assets/d3735ec8-14c1-4fed-ad54-6a5e05bdf2bf)

**checkBatteryStatus() function** is used to check whether battery is inserted into the board or not.

![Image](https://github.com/user-attachments/assets/24b2c0ed-8f3c-4963-bd55-0c0c87a721e4)

**initPeripheralsForReadings() function** sets up pins for soil moisture sensors.

![Image](https://github.com/user-attachments/assets/78363c1b-dc1f-4f1a-9a61-c74712b07804)

**takeSoilMoistureReadings() function** reads analog values, constrains them, maps to percentage, and prints them to serial monitor.

![Image](https://github.com/user-attachments/assets/54081438-2fbd-4a62-8fb3-822a07294986)

**createAndPrintPayload() function:**

This function is used to gathers all sensor data and formats it into a comma-separated string.In the payload it also sends a unique packet index which defines the packet number for each packet it sends to gateway.It's value is incremented by 1 each time at the end after the payload is sent.

![Image](https://github.com/user-attachments/assets/3a9bf15f-b087-4358-9ff8-a4934f8acf93)
![Image](https://github.com/user-attachments/assets/a800d419-ea68-4656-9d87-9f42cac2904a)


**isScheduledTime() function** determines if it's time to take a reading or not

![Image](https://github.com/user-attachments/assets/e398b3b2-031d-407f-990b-53016f4916b6)

**getTimeUntilNextScheduledReading() function** calculates how long the device should sleep until the next scheduled reading or time synchronization.

![Image](https://github.com/user-attachments/assets/2ba4a2aa-6983-42bb-9ea1-90c9568789f8)

**initializeLoRa() function** is used to configures LoRa parameters and initializes communication

![Image](https://github.com/user-attachments/assets/148cd016-0f96-46c9-bea1-7243d7ac704a)
