### ISSUE TITLE
Gateway Setup

### ISSUE THREAD

**Issue by David-Shang** [bellabaohaha/CITS5206-Gp2#52]

**Comment by David-Shang** [comment]
# Flow chart for the Gateway Setup

![Image](https://github.com/user-attachments/assets/22d80519-c838-409f-b5de-9039e5784c4f)

# Gateway Configuration and Setup

Here are all the libraries needed for use in the Gateway:
![Image](https://github.com/user-attachments/assets/efc1f66f-0023-449f-952b-a266f7a8d7cb)
![Image](https://github.com/user-attachments/assets/6369e371-cfc7-486e-a602-34fa03ee2705)
![Image](https://github.com/user-attachments/assets/caef6395-7ffe-4d0b-86e4-ddd32687aecd)

It is important to note that XPowersLib should use version 0.2.5, not the latest version 0.2.6.

The Gateway code consists of the following files:

![Image](https://github.com/user-attachments/assets/9af7b1ec-ba4b-4264-9cfd-459caa375a46)

Among these, GatewayTest.ino is the main file, while the others are configuration files. The user needs to create a local `Secrets.h` file to store the relevant AWS IoT Core configuration keys and Wi-Fi connection details (username, password).

# AWS IoT Core Configuration and Setup

First, create an object in Thing, and be sure to save the relevant keys and certificates during creation:

![Image](https://github.com/user-attachments/assets/0792ce77-3a94-450e-ad42-e756a706c6a8)

Then, create a subscription and bookmark it in the MQTT test client to receive the transmitted data.

![Image](https://github.com/user-attachments/assets/d9c12f39-057b-4977-858a-70b296ad2d17)

**Comment by asadmaza** [comment]
Closing as completed documentation for setup and testing of AWS IoT Core component.

This was based off the tutorial hyperlinked in our project specification report in "MQTT". If required feel free to look at our project specification Document [here](https://docs.google.com/document/d/e/2PACX-1vQgFZYsjV_GxjA3R-3JgrfRtF1S1AyGVZv23MqUZeG_EGrN42N-DA0dy9TNv7VEn3zz4qyqGnXIjelU/pub)

Also for handy access, specific tutorial [here](https://how2electronics.com/connecting-esp32-to-amazon-aws-iot-core-using-mqtt/) for connecting ESP 32 based boards.
